name: Backend Cache Dependencies

description: Setup backend for downstream jobs

inputs:
  WORKING-DIR:
    description: The working directory of the application
    default: .
    required: false

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version-file: ${{ inputs.WORKING-DIR }}/.python-version
    - name: Setup pipenv
      run: |
        pip install pipenv
        pipenv --version
      shell: bash
      working-directory: ${{ inputs.WORKING-DIR }}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v5
      with:
        path: ${{ inputs.WORKING-DIR }}/.venv
        key: be-venv-${{ hashFiles(format('{0}/{1}', inputs.WORKING-DIR, 'Pipfile.lock')) }} # TODO: May want to include environment and/or build run
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != true
      run: |
        echo "Cache not found, installing dependencies..."
        pipenv install --deploy --ignore-pipfile # Flags produces a more deterministic build artifact
      shell: bash
      working-directory: ${{ inputs.WORKING-DIR }}
