name: Backend Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        type: string
        default: latest
        required: true
  workflow_call:
    inputs:
      IMAGE_TAG:
        type: string
        default: latest
        required: true

env:
  WORKING-DIR: starter/backend/k8s

permissions:
  id-token: write
  contents: read

jobs:
  backend-ci:
    uses: ./.github/workflows/backend-ci.yaml
    secrets: inherit
  backend-cd:
    needs: backend-ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING-DIR }}
    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/actions
            ${{ env.WORKING-DIR }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_EKS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy application
        run: |
          #  Make sure you're kubeconfig is configured for the EKS cluster, i.e.
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
          # Set the image tag to the newer version
          kustomize edit set image backend=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MP_BACKEND_REPO }}:${{ needs.backend-ci.outputs.IMAGE-TAG || inputs.IMAGE_TAG }}
          # Apply the manifests to the cluster
          kustomize build | kubectl apply -f -
