name: CI - Movie Picture Application Frontend

on: workflow_dispatch

env:
  WORKING_DIR: starter/frontend

# Need ID token write permission to use OIDC
permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            ${{ env.WORKING_DIR }}
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ${{ env.WORKING_DIR }}/.nvmrc
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      # # Step to verify CI fails on lint errors
      # - name: Run Lint EXPECT CI FAIL
      #   run: FAIL_LINT=true npm run lint
      - name: Run Tests
        run: CI=true npm test
      # # Step to verify CI fails on test errors
      # - name: Run Tests EXPECT CI FAIL
      #   run: FAIL_TEST=true CI=true npm test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.MP_FRONTEND_REPO }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
          --build-arg=REACT_APP_MOVIE_API_URL=${{ vars.MP_BACKEND_API_URL }} \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
