name: CI/CD - Movie Picture Application

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  backend-ci:
    uses: ./.github/workflows/backend-ci.yaml
    secrets: inherit
  backend-cd:
    needs: [ backend-ci ]
    uses: ./.github/workflows/backend-cd.yaml
    with:
      IMAGE_TAG: ${{ needs.backend-ci.outputs.IMAGE-TAG }}
    secrets: inherit
  frontend-ci:
    uses: ./.github/workflows/frontend-ci.yaml
    secrets: inherit
  frontend-cd:
    needs: [ frontend-ci ]
    uses: ./.github/workflows/frontend-cd.yaml
    with:
      IMAGE_TAG: ${{ needs.frontend-ci.outputs.IMAGE-TAG }}
    secrets: inherit
