name: Frontend Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        type: string
        default: latest
        required: true
  workflow_call:
  push:
    branches:
      - main
    paths:
      - starter/frontend/**
      - .github/workflows/frontend-cd.yaml
      - .github/actions/frontend-cache-dep/**

env:
  WORKING-DIR: starter/frontend/k8s

permissions:
  id-token: write
  contents: read

jobs:
  frontend-ci:
    uses: ./.github/workflows/frontend-ci.yaml
    secrets: inherit
  frontend-cd:
    needs: frontend-ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING-DIR }}
    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/actions
            ${{ env.WORKING-DIR }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_EKS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy application
        run: |
          #  Make sure you're kubeconfig is configured for the EKS cluster, i.e.
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
          # Set the image tag to the newer version
          kustomize edit set image frontend=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MP_FRONTEND_REPO }}:${{ needs.frontend-ci.outputs.IMAGE-TAG || inputs.IMAGE_TAG }}
          # Apply the manifests to the cluster
          kustomize build | kubectl apply -f -
