name: Terraform Provisioning and Cleanup

concurrency:
  group: terraform-cleanup

on: 
  workflow_dispatch:
    inputs:
      DESTROY:
        description: Set to true to destroy resources instead of deploying
        type: boolean
        default: false

env:
  WORKING_DIR: setup/terraform

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy AWS Resources with Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            ${{ env.WORKING_DIR }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.3.9

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform deployment
        if: ${{ github.event.inputs.DESTROY != 'true' }}
        run: terraform plan

      - name: Apply Terraform deployment
        if: ${{ github.event.inputs.DESTROY != 'true' }}
        run: terraform apply -auto-approve

      - name: Destroy Terraform deployment
        if: ${{ github.event.inputs.DESTROY == 'true' }}
        run: terraform destroy -auto-approve
        